---
:tst_include_pattern:
- spec/**/*_spec.rb
:tst_exclude_pattern:
- spec/_*/**/*_spec.rb
:app_include_pattern:
- app/**/*.rb
- app/**/*.erb
- lib/**/*.rb
:app_exclude_pattern: []
:test_pattern: featu
:test_files: spec/features/wiki/wiki_spec.rb spec/features/mobile/members_spec.rb
  spec/features/members_spec.rb spec/features/members_edit_spec.rb spec/features/home_spec.rb
  spec/features/data_files_spec.rb spec/features/certs_spec.rb
:test_line: 
:command_args: 
:command: zeus rspec -O spec/spec.opts
