
#development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: bnet_development
  pool: 5
  template: template0
  username: bnet
  password: simple

test:
  adapter: postgresql
  encoding: unicode
  database: bnet_test
  pool: 5
  username: bnet
  template: template0
  password: simple

production:
  adapter: postgresql
  encoding: unicode
  database: bnet_production
  pool: 5
  username: bnet
  template: template0
  password: simple
