#!/usr/bin/env ruby

# sends an alert sms to ENV['ALERT_ADDRESSES']

require 'rubygems'
require 'ruby-debug'
require 'twilio-ruby'

require File.expand_path("../lib/env_settings", File.dirname(__FILE__))

msg = "Usage: alertwil 'body'"

debugger

abort msg unless ARGV.length == 1

body    = ARGV[0]

@account_sid = TWILIO_SMS_SID
@auth_token  = TWILIO_SMS_TOKEN

# set up a client to talk to the Twilio REST API
@client = Twilio::REST::Client.new(@account_sid, @auth_token)

@account = @client.account
@message = @account.sms.messages.create({:from => '+16504818108', :to => '650-823-0836', :body => body})
puts @message

puts "OK"
