#!/usr/bin/env ruby

# sends an alert mail to ENV['ALERT_ADDRESSES']

require 'rubygems'
require 'mail'
require File.expand_path("../lib/env_settings", File.dirname(__FILE__))

msg = "Usage: alertmail 'subject' 'body'"

abort msg unless ARGV.length == 2

subject = ARGV[0]
body    = ARGV[1]

mail = Mail.new do
  from     GMAIL_USER
  # reply_to GMAIL_USER
  to       'andy@r210.com'
  subject  "BAMRUNET #{subject}"
  body     body
end

require 'ruby-debug'
debugger
mail.delivery_method(:smtp, SMTP_SETTINGS)
mail.deliver

puts "OK"
