#!/usr/bin/env ruby

Dir.chdir "public/assets"

Dir.glob( ["*woff*", "*ttf*", "*eot*", "*svg*"] ) do |file|
  base, ext = file.split('.')
  root = base.split('-')[0]
  system "cp #{file} #{root}.#{ext}"
end
