#!/usr/bin/env ruby

# to be called after sending mail, like:
# system "script/loadmail &"

def sleep_then_load_mail(sleep_minutes)
  puts "sleeping for #{sleep_minutes} minutes..." ; STDOUT.flush
  seconds = sleep_minutes * 60
  sleep seconds
  system "script/nq 'rake ops:email:import'"
  STDOUT.flush
end

puts "STARTING LOADMAIL AT #{Time.now.to_s}"
puts "CURRENT PROCESS IS #{Process.pid}" ; STDOUT.flush

2.times { sleep_then_load_mail 3 }

4.times { sleep_then_load_mail 5 }

4.times { sleep_then_load_mail 10 }

puts "DONE at #{Time.now.to_s}" ; STDOUT.flush
