#!/usr/bin/env ruby

# to be called after sending mail, like:
# system "script/loadmail &"

def load_mail
  system "script/nq 'rake ops:email:import'"
end

def sleep_and_run(sleep_minutes)
  seconds = sleep_minutes * 60
  puts "sleeping for #{sleep_minutes} minutes..." ; STDOUT.flush
  sleep seconds
  load_mail
  STDOUT.flush
end

puts "STARTING LOADMAIL AT #{Time.now.to_s}" ; STDOUT.flush

2.times { sleep_and_run 3 }

4.times { sleep_and_run 5 }

4.times { sleep_and_run 10 }

puts "DONE." ; STDOUT.flush

