#!/usr/bin/env bash
# should be called from tmux_console

export APP="bnet_dev"
export RENV="env RUBYLIB=/home/aleak/lcl/bin/rubymine/rb/testing/patch/common:/home/aleak/lcl/bin/rubymine/rb/testing/patch/bdd"

create_new_session()
{

  cd /home/aleak/lr/BAMRU-Private

  tmux new-session -s $APP -n sysmon -d

  tmux split-window -t $APP:1 -v
  tmux send-keys -t $APP:1.1 'cls ; cd /home/aleak/lr/BAMRU-Private ; foreman start -f Procfile.dev'  C-m
  # tmux send-keys -t $APP:1.2 'cls ; cd /home/aleak/lr/BAMRU-Private ; env RUBYLIB=/home/aleak/lcl/bin/rubymine/rb/testing/patch/common:/home/aleak/lcl/bin/rubymine/rb/testing/patch/bdd zeus start' C-m

}

