---
# - hosts: all
- hosts: ekel
  sudo:  true
  vars:
    - roles_dir:    ~/.ansible_playbooks/roles       
    - lcl_user:     aleak                            
    - rem_user:     aleak
    # - rem_user:     vagrant                        
    - lcl_root:     /home/{{lcl_user}}/lr/BAMRU-Private
    - dotfile:      ${lcl_root}/.rbenv-vars-private  
    - rbenv_root:   /home/{{rem_user}}/.rbenv        
    - rbenv_vers:   ${rbenv_root}/versions
    - rbenv_cmd:    ${rbenv_root}/bin/rbenv
    - pg_user:   bnet
    - pg_pass:   ${POSTGRES_PASS}
  roles:
    - ${roles_dir}/dotdeb
    # - ${roles_dir}/cli_base
    # - ${roles_dir}/cli_user 
    # - ${roles_dir}/rbenv
    # - ${roles_dir}/rbgems
    # - ${roles_dir}/cli_util
    - ${roles_dir}/postgres
    - ${roles_dir}/postgres_user 
    # - ${roles_dir}/nginx
    # - ${roles_dir}/redis
    # - ${roles_dir}/memcached

